services:
  # Backend API service
  - type: web
    name: cse6-poll-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
    routes:
      - type: rewrite
        source: /api/*
        destination: /*

  # Static site (frontend)
  - type: web
    name: cse6-poll-frontend
    env: static
    buildCommand: echo "No build step required"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: API_URL
        fromService:
          name: cse6-poll-api
          type: web
          property: url 