services:
  # Backend API service
  - type: web
    name: cse6-poll-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
    autoDeploy: true
    routes:
      - type: rewrite
        source: /api/*
        destination: /*

  # Static site (frontend)
  - type: web
    name: cse6-poll-frontend
    env: static
    buildCommand: echo "No build step required"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /api/*
        destination: https://cse6-poll-api.onrender.com/api/:splat
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: API_URL
        value: https://cse6-poll-api.onrender.com/api 